
{
    'name': 'Opera Manufacture Customize',
    'summary': 'Opera Manufacture Customize',
    'author': "ITSS , Mahmoud Elfeky",
    'company': 'ITSS',
    'website': "http://www.itss-c.com",
    'version': '14.0.0.1.0',
    'category': 'Manufacture',
    'license': 'AGPL-3',
    'sequence': 1,
    'depends': [
        'base',
        'mrp',
        'hr',
        # 'branch',
        'sale',
        'purchase',
        'purchase_mrp',
        'stock',
        'mrp_workorder',
        'mo_reset',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        # 'report/',
        # 'wizard/',
        'views/employee_shift.xml',
        'views/hr_employee.xml',
        'views/mrp_production.xml',
        'views/product_template.xml',
        'views/mrp_workcenter.xml',
        # 'views/sale_order.xml',
        'views/stock_picking.xml',
        'views/purchase_order.xml',
        # 'data/',
    ],
    'demo': [
        # 'demo/',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}

